name: Format Fix
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: write
  pull-requests: write
jobs:
  fix:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@b315a4d9881690c63d53fc0175b150a3776140bd
        with:
          version: '1'
      - run: make format-fix
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          token: ${{  secrets.GITHUB_TOKEN }}
          commit-message: '🤖 Automatically format the source code files'
          title: '🤖 Automatically format the source code files'
          body: |-
            This pull request formats the source code files using the JuliaFormatter package.

            Note: CI will not automatically run on this PR. Please open and close this PR to trigger CI.
          branch: bot/format/${{ github.ref }}
          delete-branch: true
